name: validate token logos

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  validate-logo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        id: branch-name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Dependencies 
        run: yarn

      - name: Run LogoURI Validation test
        run: yarn validate:logo ${{ steps.branch-name.outputs.branch }}